global:
  podSecurityStandards:
    enforced: false

kube-vip:
  enabled: true
  env:
    vip_interface: "ens192"
  image:
    repository: gsoci.azurecr.io/giantswarm/kube-vip
  nameOverride: kube-vip-svc-lb
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

kube-vip-cloud-provider:
  enabled: true
  rangeGlobal: ""
  cidrGlobal: ""
  image:
    repository: gsoci.azurecr.io/giantswarm/kube-vip-cloud-provider
  nameOverride: kube-vip-cloud-provider
