name: cloud-provider-proxmox
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/cloud-provider-proxmox-app
  tag: v0.0.1
  pullPolicy: IfNotPresent
